#!/usr/bin/env python3
"""ONLINE (PC addition): geometry tables and art manifest for the browser NPC port.

Reads the display trees of the browser game's NPCSprite1..16 library symbols (the posable
"non-player character" skins, editor/specials/npcsprites) through FlashPartRender.java `tree`
and writes
  src/online/items/npc/NPCSpriteData.inc   placement matrices, hit-shape scales, pelvis height,
                                           spineRef and draw order per skin (numbers only)
  tools/assets/flash_items/npc.txt         the body-part frames / gore chunks to render
                                           (extract_flash_items.py manifest, clip:<id> entries)
Run once when the SWF changes:  python tools/assets/gen_npc_tables.py
"""
import math
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SWF = os.path.join(REPO, 'binary', 'flash', 'swf', 'game_e_v1_87_g.dec.swf')
FFDEC = os.path.join(REPO, 'binary', 'flash', 'tools', 'ffdec')
CLS = 'com.totaljerkface.game.editor.specials.npcsprites.NPCSprite%d'
COUNT = 16
TOP = ['headOuter', 'chest', 'pelvis', 'arm1', 'arm2', 'leg1', 'leg2']


class Tree:
    def __init__(self, text):
        self.roots, self.frames, self.places, self.bounds = [], {}, {}, {}
        for line in text.splitlines():
            p = line.split()
            if not p:
                continue
            if p[0] == 'ROOT':
                self.roots.append(int(p[1]))
            elif p[0] == 'S':
                self.frames[int(p[1])] = int(p[2])
            elif p[0] == 'P':
                clip, fr, depth, ch = map(int, p[1:5])
                a, b, c, d = map(float, p[9:13])
                self.places.setdefault((clip, fr), []).append(dict(
                    depth=depth, ch=ch, name=p[6], m=(a, b, c, d, int(p[7]) / 20.0, int(p[8]) / 20.0)))
            elif p[0] == 'B':
                self.bounds[int(p[1])] = tuple(int(v) / 20.0 for v in p[2:6])

    def child(self, clip, name, frame=1):
        for e in self.places.get((clip, frame), []):
            if e['name'] == name:
                return e
        raise KeyError('%d/%s@%d' % (clip, name, frame))

    def rect(self, ch, frame=1):
        """Bounds of a character's frame (DisplayObject.getBounds of its own space)."""
        if ch not in self.frames:
            return self.bounds.get(ch)
        r = None
        for e in self.places.get((ch, frame), []):
            cr = self.rect(e['ch'])
            if cr is None:
                continue
            a, b, c, d, tx, ty = e['m']
            xs, ys = [], []
            for x, y in ((cr[0], cr[1]), (cr[2], cr[1]), (cr[0], cr[3]), (cr[2], cr[3])):
                xs.append(a * x + c * y + tx)
                ys.append(b * x + d * y + ty)
            n = (min(xs), min(ys), max(xs), max(ys))
            r = n if r is None else (min(r[0], n[0]), min(r[1], n[1]), max(r[2], n[2]), max(r[3], n[3]))
        return r


def run_tree():
    lib = os.path.join(FFDEC, 'lib')
    cp = os.pathsep.join([os.path.join(lib, 'ffdec_lib.jar'), os.path.join(lib, '*')])
    with tempfile.TemporaryDirectory() as work:
        path = os.path.join(work, 'commands.txt')
        with open(path, 'w') as f:
            f.write(''.join('tree %s\n' % (CLS % i) for i in range(1, COUNT + 1)))
        res = subprocess.run(['java', '-Djava.awt.headless=true', '-cp', cp,
                              os.path.join(HERE, 'FlashPartRender.java'), SWF, path],
                             capture_output=True, text=True)
    if res.returncode != 0:
        sys.exit(res.stderr[-2000:])
    return Tree(res.stdout)


def flt(v):
    s = '%.7g' % v
    if '.' not in s and 'e' not in s:
        s += '.0'
    return s + 'f'


def mat(e):
    return '{%s}' % ', '.join(flt(v) for v in e['m'])


def scale(e):
    a, b, c, d = e['m'][:4]
    return '{%s, %s}' % (flt(math.hypot(a, b)), flt(math.hypot(c, d)))


def main():
    t = run_tree()
    rows = []
    manifest = ['# ONLINE (PC addition): browser NPC skins (generated by gen_npc_tables.py, do not edit).',
                '# <name> clip:<character id> [frame] [zoom] [hide=depths]  # path in the NPCSprite symbol']
    for i, root in enumerate(t.roots, 1):
        cls = CLS % i

        def C(clip, name, fr=1):
            return t.child(clip, name, fr)

        ho = C(root, 'headOuter')
        head = C(ho['ch'], 'head')
        chest = C(root, 'chest')
        pelvis = C(root, 'pelvis')
        arm = [C(root, 'arm1'), C(root, 'arm2')]
        leg = [C(root, 'leg1'), C(root, 'leg2')]
        ua = [C(arm[k]['ch'], 'upperArm%d' % (k + 1)) for k in range(2)]
        lao = [C(arm[k]['ch'], 'lowerArmOuter%d' % (k + 1)) for k in range(2)]
        la = [C(lao[k]['ch'], 'lowerArm%d' % (k + 1)) for k in range(2)]
        ul = [C(leg[k]['ch'], 'upperLeg%d' % (k + 1)) for k in range(2)]
        llo = [C(leg[k]['ch'], 'lowerLegOuter%d' % (k + 1)) for k in range(2)]
        ll = [C(llo[k]['ch'], 'lowerLeg%d' % (k + 1)) for k in range(2)]

        def shape(e):
            return C(e['ch'], 'shape')

        # pelvis.height in NPCSprite space (frame 1, hit shape included as in Flash).
        pr = t.rect(pelvis['ch'])
        a, b, c, d, tx, ty = pelvis['m']
        ys = [b * x + d * y + ty for x in (pr[0], pr[2]) for y in (pr[1], pr[3])]
        pelvis_h = max(ys) - min(ys)
        spine = C(chest['ch'], 'spineRef', 2)['m']
        order = sorted(range(7), key=lambda k: C(root, TOP[k])['depth'])
        rows.append(
            '    {  // NPCSprite%d\n' % i +
            '        %s,\n        %s,\n        %s,\n        %s,\n' % (mat(ho), mat(head), mat(chest), mat(pelvis)) +
            ''.join('        {%s, %s},\n' % (mat(x[0]), mat(x[1])) for x in (arm, ua, lao, la, leg, ul, llo, ll)) +
            '        %s, %s, %s,\n' % (scale(shape(head)), scale(shape(chest)), scale(shape(pelvis))) +
            ''.join('        {%s, %s},\n' % (scale(shape(x[0])), scale(shape(x[1]))) for x in (ua, la, ul, ll)) +
            '        %s, {%s, %s}, {%s}},\n' % (flt(pelvis_h), flt(spine[4]), flt(spine[5]),
                                                ', '.join(map(str, order))))

        # Art: part frames without the hit-shape / spineRef guides, plus the gore chunks.
        def hide(clip, fr):
            return ','.join(str(e['depth']) for e in t.places.get((clip, fr), [])
                            if e['name'] in ('shape', 'spineRef')) or '-'

        def part(name, path, clip, frames):
            for fr in frames:
                manifest.append('npc%d_%s_%d clip:%d %d zoom=2 hide=%s  # NPCSprite%d/%s'
                                % (i, name, fr, clip, fr, hide(clip, fr), i, path))

        part('head', 'headOuter/head', head['ch'], [1, 2])
        part('chest', 'chest', chest['ch'], range(1, 9))
        part('pelvis', 'pelvis', pelvis['ch'], range(1, 5))
        for k in range(2):
            n = k + 1
            part('upperArm%d' % n, 'arm%d/upperArm%d' % (n, n), ua[k]['ch'], range(1, 5))
            part('lowerArm%d' % n, 'arm%d/lowerArmOuter%d/lowerArm%d' % (n, n, n), la[k]['ch'], [1, 2])
            part('upperLeg%d' % n, 'leg%d/upperLeg%d' % (n, n), ul[k]['ch'], range(1, 5))
            part('lowerLeg%d' % n, 'leg%d/lowerLegOuter%d/lowerLeg%d' % (n, n, n), ll[k]['ch'], [1, 2])
        for path, fr, names in (('headOuter/head', 3, ['chunk1', 'chunk2', 'chunk3', 'chunk4', 'brain']),
                                ('chest', 9, ['chunk1', 'chunk2', 'chunk3', 'chunk4', 'heart']),
                                ('pelvis', 5, ['chunk1', 'chunk2', 'chunk3'])):
            pname = path.split('/')[-1]
            pclip = head['ch'] if pname == 'head' else chest['ch'] if pname == 'chest' else pelvis['ch']
            for nm in names:
                manifest.append('npc%d_%s_%s clip:%d 1 zoom=2  # NPCSprite%d/%s@%d/%s'
                                % (i, pname, nm, C(pclip, nm, fr)['ch'], i, path, fr, nm))

    inc = os.path.join(REPO, 'src', 'online', 'items', 'npc', 'NPCSpriteData.inc')
    with open(inc, 'w', newline='\n') as f:
        f.write('// ONLINE (PC addition): generated by tools/assets/gen_npc_tables.py from the browser game\'s\n'
                '// NPCSprite1..16 symbols (layout: NPCSpriteData.h). Do not edit.\n')
        f.write(''.join(rows))
    man = os.path.join(HERE, 'flash_items', 'npc.txt')
    with open(man, 'w', newline='\n') as f:
        f.write('\n'.join(manifest) + '\n')
    print('wrote %s and %s (%d art entries)' % (inc, man, len(manifest) - 2))


if __name__ == '__main__':
    main()
